-- 专区表
CREATE TABLE `SPECIALLY_ZONE` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '专区ID',
  `SPECIALLY_ZONE_NAME` varchar(64) NOT NULL COMMENT '专区名称',
  `SPECIALLY_ZONE_PIC_URL` varchar(300) DEFAULT NULL COMMENT '专区图标地址',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `LAST_TIME` datetime DEFAULT NULL COMMENT '最后修改时间',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '修改人',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='专区表';

-- 类目表
CREATE TABLE `CATEGORY` (
  `ID` bigint(10) NOT NULL AUTO_INCREMENT COMMENT '类目ID',
  `CATEGORY_NAME` varchar(64) NOT NULL COMMENT '类目名称',
  `CATEGORY_PICTURE_RUL` varchar(64) NOT NULL COMMENT '类目图片地址',
  `CATEGORY_DESCRIPTION` varchar(500) NOT NULL COMMENT '类目描述',
  `PID` bigint(20) NOT NULL  COMMENT '父类目ID',
  `CATEGORY_IS_LEAF` tinyint(4) not null comment '是否叶子类目0：不是，1：是',
  `CATEGORY_LEVEL` tinyint(4) not null comment '类目层级',
  `ORDER_LIST` tinyint(4) default null comment '类目排序',
  `CATEGORY_ID_PATH` varchar(100) default null comment '类目ID全路径',
  `CATEGORY_NAME_PATH` varchar(100) default null comment '类目名称全路径',
  `IS_VISIBLE` tinyint(4) not null comment '是否可见0：不可见，1：可见',
  `QUANTITY_UNIT` varchar(10) not null comment '数量单位',  
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `LAST_TIME` datetime DEFAULT NULL COMMENT '最后修改时间',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '修改人',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='类目表';



-- 属性词典表
CREATE TABLE `DIM_ATTRIBUTE_LIBRARY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '属性ID',
  `ATTRIBUTE_NAME` varchar(100) DEFAULT NULL,'属性名称',
  `ATTRIBUTE_VALUE` varchar(100) DEFAULT NULL,'属性值，多值用逗号隔开',
  `ATTRIBUTE_TYPE` tinyint(4) DEFAULT 0,'属性类型 0：其他，1：颜色 2：尺寸',
  `ATTRIBUTE_SELECT_TYPE` tinyint(4) DEFAULT 0,'属性选择类型 0:唯一属性 0：单选 1：复选',
  `CATEGORY_ID` bigint(20) NOT NULL COMMENT '属性所属类目,0为所有类目',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '修改人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `LAST_TIME` datetime NOT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`ID`),
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='属性词典表';



-- 商品表
CREATE TABLE `GOODS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `CATEGORY_ID` bigint(10) NOT NULL COMMENT '类目ID',
  `BRAND_ID` bigint(10) NOT NULL COMMENT '品牌ID',
  `GOODS_NAME` varchar(200) NOT NULL COMMENT '商品名称',
  `GOODS_TITLE` varchar(200) NOT NULL COMMENT '商品标题',
  `GOODS_SPEC` varchar(500) DEFAULT NULL COMMENT '商品规格',
  `GOODS_PACK` varchar(500) DEFAULT NULL COMMENT '商品包装售后',
  `GOODS_PRICE` decimal(11,8) NOT NULL DEFAULT '0.00' COMMENT '商品参考价格',
  `GOODS_MAIN_PICTURE_URL` varchar(300) DEFAULT NULL COMMENT '商品主图地址',
  `GOODS_PICTURE_URL` varchar(300) DEFAULT NULL COMMENT '商品轮播图片地址，多个图片用,号割开',
  `GOODS_DESCRIPTION` varchar(1000) DEFAULT NULL COMMENT '商品详情描述 ',
  `GOODS_DESCRIPTION_PICTURE_URL` varchar(100) DEFAULT NULL COMMENT '商品描述图片，多个图片用,号割开',
  `FREIGHT_TEMPLATE_ID` tinyint(4) NOT NULL DEFAULT '0' COMMENT '运费模板ID',
  `GOODS_STATUS` tinyint(4) NOT NULL DEFAULT '0' COMMENT '商品状态0:上架,1:下架',
  `IS_VISIBLE` tinyint(4) not null comment '是否可见0：不可见，1：可见',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='商品表';



--商品SKU表
CREATE TABLE `GOODS_SKU` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `SKU_CODE` varchar(100) NOT NULL COMMENT '商品sku（类目3+商品5+流水3+颜色2+尺码2）',
  `IN_PRICE` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '商品定价',
  `GOODS_ACTIVITY_PRICE` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '商品活动价',
  `GOODS_SALE_PRICE` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '商品售价',
  `STOCK_NUM` bigint(20) NOT NULL COMMENT '库存',
  `STOCK_FREEZE_NUM` bigint(20) NOT NULL COMMENT '冻结库存',
  `STOCK_AVAILABLE_NUM` bigint(20) NOT NULL COMMENT '剩余库存',
  `GOODS_COLOR` varchar(20) NOT NULL COMMENT '商品颜色',
  `GOODS_SIZE` varchar(20) NOT NULL COMMENT '商品尺码',
  `GOODS_SKU_STATUS` tinyint(4) NOT NULL DEFAULT '0' COMMENT '商品SKU状态0:上架,1:下架',
  `GOODS_OPERATOR_ID` bigint(20) NOT NULL COMMENT '商品所有者',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `VERSION` int(11) DEFAULT NULL COMMENT '版本号（每次关键信息更新都会+1）',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='商品SKU表';


-- 商品属性表
CREATE TABLE `PRODUCT_ATTRIBUTE_LIBRARY` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `ATTRIBUTE_ID `bigint(20) NOT NULL COMMENT '属性字典ID',
  `ATTRIBUTE_NAME` varchar(200) DEFAULT NULL,'属性名称',
  `ATTRIBUTE_LIBRARY_VALUE` varchar(500) NOT NULL COMMENT '属性值 {ID1:value1, ID2:value2, ID3:value3}',
  `ATTRIBUTE_SELECT_TYPE` tinyint(4) DEFAULT 0,'属性选择类型 0:唯一属性 0：单选 1：复选',
  `ATTRIBUTE_TYPE` tinyint(4) DEFAULT 0,'属性类型 0：其他，1：颜色 2：尺寸',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='商品属性表';


-- 商品批发价格
CREATE TABLE `WHOLESALE_PRICE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `STOCK_NUM` bigint(20) NOT NULL COMMENT '库存',
  `SKU_CODE` varchar(100) NOT NULL COMMENT '商品sku（类目2+商品5+流水3+颜色2+尺码2）',
  `GOODS_WHOLESALE_PRICE` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '商品批发价',
  `MIN_BUY_NUM` bigint(11) NOT NULL DEFAULT '1' COMMENT '最小购买数量',
  `MAX_BUY_NUM` bigint(11) NOT NULL DEFAULT '1' COMMENT '最大购买数量',
  `QUOTAS` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '配额',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='商品批发价格';


--商品专区关联表
CREATE TABLE `SPECIALLY_ZONE_GOODS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `SPECIALLY_ZONE_ID` bigint(20) NOT NULL COMMENT '专区ID',
  `IS_VISIBLE` tinyint(4) not null comment '是否可见0：不可见，1：可见',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='商品专区关联表';

--品牌表
CREATE TABLE `BRAND` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BRAND_NAME` varchar(255) NOT NULL COMMENT '品牌名称',
  `FIRST_LETTER` char(1) NOT NULL COMMENT '品牌首字母',
  `BRAND_PICTURE_URL` varchar(300) DEFAULT NULL COMMENT '品牌主图地址',
  `IS_DELETED` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CREATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '创建人',
  `UPDATE_OPERATOR_ID` bigint(20) NOT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime NOT NULL COMMENT '最后一次更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='品牌表';


--购物车
CREATE TABLE `CART` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `USER_ID` bigint(20) NOT NULL COMMENT '用户ID',
  `CART_CONTENT` varchar(3000) NOT NULL COMMENT '购物车内容，以json格式储存',
  `CLIENT_IP` varchar(50) DEFAULT NULL COMMENT '客户端IP',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='购物车';


-- 订单表
CREATE TABLE `GOODS_ORDER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDER_CODE` varchar(20) NOT NULL COMMENT '订单编号',
  `ORDER_AMOUNT` decimal(12,2) NOT NULL COMMENT '订单金额(产品总额+运费)',
  `PRODUCT_AMOUNT` decimal(12,2) NOT NULL COMMENT '产品总额',
  `USER_ID` bigint(20) NOT NULL COMMENT '用户ID',
  `ORDER_DELIVERY_FEE` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
  `ORDER_STATUS` tinyint(4) NOT NULL COMMENT '订单状态 100：待付款；101：已付款；102：待发货；103：已发货；104 : 代签收 ; 105：已签收；106：订单完成；201：已取消；202：配送失败',
  `ORDER_CREATE_TIME` datetime NOT NULL COMMENT '订单创建时间',
  `ORDER_PAYMENT_datetime` datetime DEFAULT NULL COMMENT '付款时间',
  `ORDER_CONFIRM_TIME` datetime DEFAULT NULL COMMENT '订单审核时间',
  `ORDER_CONFIRM_BY` bigint(20) DEFAULT NULL COMMENT '订单审核人ID',
  `DELIVERY_datetime` datetime DEFAULT NULL COMMENT '发货时间',
  `RECEIVE_TIME` datetime DEFAULT NULL COMMENT '收货时间',
  `CANCEL_datetime` datetime DEFAULT NULL COMMENT '订单取消时间',
  `ORDER_CANCEL_REASION` bigint(20) DEFAULT NULL COMMENT '取消原因',
  `GOODS_RECEIVER_NAME` varchar(50) DEFAULT NULL COMMENT '收货人姓名',
  `GOODS_RECEIVER_PROVINCE` varchar(50) DEFAULT NULL COMMENT '收货人省份',
  `GOODS_RECEIVER_CITY` varchar(50) DEFAULT NULL COMMENT '收货人城市',
  `GOODS_RECEIVER_COUNTY` varchar(100) DEFAULT NULL COMMENT '收货人地区',
  `GOODS_RECEIVER_AREA` varchar(500) DEFAULT NULL COMMENT '收货人四级区域',
  `GOODS_RECEIVER_ADDRESS` varchar(500) DEFAULT NULL COMMENT '收货人详细地址',
  `GOODS_RECEIVER_POST_CODE` varchar(20) DEFAULT NULL COMMENT '收货人邮编',
  `GOODS_RECEIVER_PHONE` varchar(20) DEFAULT NULL COMMENT '收货人手机号',
  `DELIVERY_COMPANY_ID` bigint(20) DEFAULT NULL COMMENT '配送公司ID',
  `DELIVERY_CODE` varchar(50) DEFAULT NULL COMMENT '配送单号',
  `DELIVERY_COMPANY_NAME` varchar(100) DEFAULT NULL COMMENT '配送公司名称',
  `INVOICE_TITLE` varchar(50) DEFAULT NULL COMMENT '发票抬头',
  `INVOICE_TYPE` tinyint(2) DEFAULT NULL COMMENT '发票类型（1：普通发票 2：增值税发票）',
  `CUSTOMER_MESSAGE` varchar(500) DEFAULT NULL COMMENT '顾客留言',
  `CONFIRM_STATUS` tinyint(4) NOT NULL DEFAULT '1' COMMENT '0：审核失败；1：待审核；2：审核通过',
  `EXPECT_DELIVERY_TIME` tinyint(4) DEFAULT NULL COMMENT '期望配送时间段，"0":"不限时间送货","1":"仅工作日送货","2":"仅双休日、节假日送货"',
  `ORDER_PAYMENT_STATUS` tinyint(4) NOT NULL COMMENT '订单支付状态，0：未支付；1：已支付',
  `ORDER_COMPLETE_TIME` datetime DEFAULT NULL COMMENT '订单完成时间',
  `ORDER_COMPLETE_BY` bigint(20) DEFAULT NULL COMMENT '完成操作人',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `UPDATE_BY` bigint(20) DEFAULT NULL COMMENT '更新人',
  `DELIVERY_TYPE` tinyint(4) DEFAULT NULL COMMENT '配送方式，1：快递配送；2：现场给货；3：营业厅自提',
  `GOOD_RECEIVER_EMAIL` varchar(300) DEFAULT NULL COMMENT '收货人邮箱',
  `ORDER_PAYMENT_GATWAY` tinyint(4) DEFAULT '1' COMMENT '支付网关：0保证金 1积分 2支付宝 3微信 4银联',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='订单表';



--订单详情表
CREATE TABLE `ORDER_ITEM` (
  `ID` bigint(20) NOT NULL,
  `GOODS_ID` bigint(20) DEFAULT NULL COMMENT '商品ID',
  `SKU_CODE` varchar(32) NOT NULL COMMENT '商品sku（类目2+商品5+流水3+颜色2+尺码2）',
  `GOODS_PRICES` decimal(12,2) DEFAULT NULL COMMENT '商品单价',
  `GOODS_ATTRIBUTE` varchar(100) NOT NULL COMMENT '商品属性，多个属性用,号隔开',
  `ORDER_ID` bigint(20) NOT NULL COMMENT '订单ID',
  `GOODS_NAME` varchar(200) NOT NULL COMMENT '商品名称',
  `GOODS_PRICE` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '商品价格',
  `NUM` int(10) DEFAULT NULL COMMENT '商品购买数量',
  `TOTAL_AMOUNT` decimal(20,2) DEFAULT NULL COMMENT '商品总金额',
  `GOODS_OPERATOR_ID` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '商品所有者ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单详情表';


--配送公司表
CREATE TABLE `STANDARD_DELIVERY_SUPPLIER` (
  `ID` bigint(20) NOT NULL COMMENT '标准配送公司ID',
  `COMPANY_CNAME` varchar(500) NOT NULL COMMENT '标准配送公司名称',
  `HOME_URL` varchar(500) NOT NULL COMMENT '标准配送公司URL',
  `STATUS` int(11) NOT NULL COMMENT '开启状态 0：关闭 1：启用',
  `DELIVERY_SUPPLIER_KEY` varchar(100) DEFAULT NULL COMMENT '关键词',
  `CREATE_BY` int(11) NOT NULL COMMENT '创建人',
  `UPDATE_BY` int(11) DEFAULT NULL COMMENT '更新人',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `IS_DELETEDD` int(11) NOT NULL COMMENT '是否删除 0：未删除 1：已删除',
  `DELIVERY_RULES` varchar(100) DEFAULT NULL COMMENT '运单号规则',
  `DELIVERY_RULES_REMARK` varchar(500) DEFAULT NULL COMMENT '运单号规则说明',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='标准配送公司表';

-- 市
CREATE TABLE `CITY` (
  `CITY_ID` int(9) NOT NULL AUTO_INCREMENT,
  `CITY_CNAME` varchar(100) NOT NULL,
  `CITY_ENAME` varchar(100) DEFAULT NULL,
  `PROVINCE_ID` int(11) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `UPDATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `IS_DELETEDD` tinyint(4) DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `CITY_CNAME_EFIRST` char(2) NOT NULL,
  `SORT` int(11) DEFAULT NULL,
  PRIMARY KEY (`CITY_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='市';


-- 区/县
CREATE TABLE `COUNTY` (
  `COUNTY_ID` int(9) NOT NULL AUTO_INCREMENT,
  `COUNTY_ENAME` varchar(100) DEFAULT NULL,
  `COUNTY_CNAME` varchar(100) NOT NULL,
  `CITY_ID` int(11) NOT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `UPDATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `IS_DELETEDD` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `SORT` int(11) DEFAULT NULL,
  PRIMARY KEY (`COUNTY_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='区/县';


-- 省
CREATE TABLE `PROVINCE` (
  `PROVINCE_ID` int(9) NOT NULL AUTO_INCREMENT,
  `PROVINCE_ENAME` varchar(100) DEFAULT NULL,
  `PROVINCE_CNAME` varchar(100) NOT NULL,
  `COUNTRY_ID` int(11) NOT NULL DEFAULT '1',
  `PINYIN` varchar(100) DEFAULT NULL,
  `CREATE_TIME` datetime NOT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `UPDATE_OPERATOR_ID` int(11) DEFAULT NULL,
  `IS_DELETEDD` tinyint(4) DEFAULT '0' COMMENT '是否删除  1：是 0：否',
  `PROVINCE_CNAME_EFIRST` char(2) NOT NULL,
  `SORT` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROVINCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='省';


-- 支付信息
CREATE TABLE `PAY_INFO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '支付ID',
  `TRADE_NO` varchar(100) DEFAULT NULL COMMENT '交易流水号',
  `ORDER_CODE` varchar(100) DEFAULT NULL COMMENT '支付平台提交订单编码',
  `ORDER_NUM` varchar(100) DEFAULT NULL COMMENT '订单号',
  `CALLER_CODE` varchar(20) DEFAULT NULL COMMENT '资格码',
  `ORDER_AMOUNT` decimal(12,2) DEFAULT NULL COMMENT '金额',
  `ORDER_SUBJECT` varchar(300) DEFAULT NULL COMMENT '订单名称',
  `ORDER_BODY` varchar(300) DEFAULT NULL COMMENT '商品名称',
  `PAY_TYPE` int(3) DEFAULT NULL COMMENT '支付方式 1:积分 2:支付宝 3:微信',
  `PAY_STATUS` int(2) DEFAULT NULL COMMENT '支付是否成功 1:成功 0:失败',
  `REMARK` varchar(200) DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '支付时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  `PAY_TO_NO` varchar(20) DEFAULT NULL COMMENT '卖方帐号',
  `IS_SYNC` int(2) DEFAULT NULL COMMENT '是否已经推送 1:是 0:否',
  `SYNC_NUM` int(5) DEFAULT NULL COMMENT '推送调用方次数,最多10次',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='支付信息表';


--用户地址表
CREATE TABLE `ADDRESS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(50) DEFAULT NULL COMMENT '用户ID',
  `province_ID` VARCHAR(10) DEFAULT NULL COMMENT '省',
  `CITY_ID` VARCHAR(10) DEFAULT NULL COMMENT '市',
  `TOWN_ID` VARCHAR(10) DEFAULT NULL COMMENT '县/区',
  `MOBILE` VARCHAR(255) DEFAULT NULL COMMENT '手机',
  `ADDERSS` VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
  `CONTACT` VARCHAR(255) DEFAULT NULL COMMENT '联系人',
  `IS_DEFAULT` VARCHAR(1) DEFAULT NULL COMMENT '是否是默认 1默认 0否',
  `NOTES` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `CREATE_DATETIME` datetime DEFAULT NULL COMMENT '创建日期',
  `ALIAS` VARCHAR(50) DEFAULT NULL COMMENT '别名',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='用户地址表';